name: BibLaTeX CI
  
# Controls when the action will run. 
on:
  schedule:
   - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Install TeXLive
         run: |
           sudo apt-get install texlive-full

       - name: Set ENV
         run: |

       - name: Checkout DEV
         uses: actions/checkout@v2

       - name: Run biblatex tests
         run: |
           
