name: BibLaTeX CI

env:
  TLURL: http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  TEXDIR: $RUNNER_WORKSPACE/texlive/2020
  TEXMFLOCAL: $RUNNER_WORKSPACE/texlive/texmf-local
  TEXMFSYSVAR: $RUNNER_WORKSPACE/texlive/2020/texmf-var
  TEXMFSYSCONFIG: $RUNNER_WORKSPACE/texlive/2020/texmf-config
  
# Controls when the action will run. 
on:
  schedule:
   - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Install TeXLive
         run: |
           echo Downloading and compiling in [$PWD] from [$TLURL]

           mkdir tl
           wget -nc $TLURL
           tar -xf $(basename $TLURL) --strip-components=1 --directory=tl

           pushd tl
           perl install-tl -scheme medium
           popd

#       - name: Set ENV
#         run: |
#           echo "$RUNNER_WORKSPACE/localperl/bin" >> $GITHUB_PATH
#           echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RUNNER_WORKSPACE/localperl/lib" >> $GITHUB_ENV

#       - name: Checkout DEV
#         uses: actions/checkout@v2

 #      - name: Install Biber Dependencies Without Test
 #        run: |
 #          cpan -T Module::Build
 #          perl Build.PL
 #          ./Build installdeps --cpan_client "cpan -T"

#       - name: Run biber tests
#         run: |
#           ./Build test
