name: BibLaTeX CI

env:
  TLURL: http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  
# Controls when the action will run. 
on:
  schedule:
   - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Set ENV
         run: |
           echo "TEXLIVE_INSTALL_PREFIX=$RUNNER_WORKSPACE/texlive" >> $GITHUB_ENV
           echo "TEXLIVE_INSTALL_TEXDIR=$RUNNER_WORKSPACE/texlive/2020" >> $GITHUB_ENV
           echo "TEXLIVE_INSTALL_TEXMFLOCAL=$RUNNER_WORKSPACE/texlive/texmf-local" >> $GITHUB_ENV
           echo "TEXLIVE_INSTALL_TEXMFSYSVAR=$RUNNER_WORKSPACE/texlive/2020/texmf-var" >> $GITHUB_ENV
           echo "TEXLIVE_INSTALL_TEXMFSYSCONFIG=$RUNNER_WORKSPACE/texlive/2020/texmf-config" >> $GITHUB_ENV
           echo "TEXDIR=$RUNNER_WORKSPACE/texlive/2020" >> $GITHUB_ENV
           echo "TEXMFLOCAL=$RUNNER_WORKSPACE/texlive/texmf-local" >> $GITHUB_ENV
           echo "TEXMFSYSVAR=$RUNNER_WORKSPACE/texlive/2020/texmf-var" >> $GITHUB_ENV
           echo "TEXMFSYSCONFIG=$RUNNER_WORKSPACE/texlive/2020/texmf-config" >> $GITHUB_ENV                                            

       - name: Install TeXLive
         run: |
           echo Downloading and compiling in [$PWD] from [$TLURL]

           mkdir tl
           wget -nc $TLURL
           tar -xf $(basename $TLURL) --strip-components=1 --directory=tl

           pushd tl
           perl install-tl -scheme medium
           popd

#       - name: Checkout DEV
#         uses: actions/checkout@v2

 #      - name: Install Biber Dependencies Without Test
 #        run: |
 #          cpan -T Module::Build
 #          perl Build.PL
 #          ./Build installdeps --cpan_client "cpan -T"

#       - name: Run biber tests
#         run: |
#           ./Build test
